# 多仓库配置列表
# 格式说明：每个仓库需包含 repo_owner（所有者）、repo_name（仓库名）、base_save_dir（基础保存目录）、state_key（状态标识）
repos:
  - repo_owner: "SychicBoy"          # 仓库所有者（GitHub用户名/组织名）
    repo_name: "NETReactorSlayer"    # 仓库名称
    base_save_dir: "./Releases"      # 基础保存目录（文件最终会按「基础目录/仓库名/版本号」存储）
    state_key: "NETReactorSlayer"    # 状态文件中的唯一标识（避免与其他仓库冲突）

  - repo_owner: "dnSpy"
    repo_name: "dnSpy"
    base_save_dir: "./Releases"
    state_key: "dnSpy"
    
  - repo_owner: "LeeYiY"
    repo_name: "chrome_installer"
    base_save_dir: "./Releases"
    state_key: "chrome_installer"
    
  - repo_owner: "LeeYiY"
    repo_name: "edge_installer"
    base_save_dir: "./Releases"
    state_key: "edge_installer"

  - repo_owner: "kingToolbox"
    repo_name: "WindTerm"
    base_save_dir: "./Releases"
    state_key: "WindTerm"
    
  - repo_owner: "x64dbg"
    repo_name: "x64dbg"
    base_save_dir: "./Releases"
    state_key: "x64dbg"

  - repo_owner: "NickeManarin"
    repo_name: "ScreenToGif"
    base_save_dir: "./Releases"
    state_key: "ScreenToGif"

  - repo_owner: "notepad-plus-plus"
    repo_name: "notepad-plus-plus"
    base_save_dir: "./Releases"
    state_key: "notepad-plus-plus"

  - repo_owner: "o0HalfLife0o"
    repo_name: "TVBoxOSC"
    base_save_dir: "./Releases"
    state_key: "TVBox_takagen99"

  - repo_owner: "tnodir"
    repo_name: "fort"
    base_save_dir: "./Releases"
    state_key: "Fort_Firewall"


  - repo_owner: "Ventoy"
    repo_name: "Ventoy"
    base_save_dir: "./Releases"
    state_key: "Ventoy"

  - repo_owner: "BlackINT3"
    repo_name: "OpenArk"
    base_save_dir: "./Releases"
    state_key: "OpenArk"


  - repo_owner: "skylot"
    repo_name: "jadx"
    base_save_dir: "./Releases"
    state_key: "jadx"
    
  - repo_owner: "opentrack"
    repo_name: "opentrack"
    base_save_dir: "./Releases"
    state_key: "opentrack"
