# 多仓库配置列表
# 格式说明：每个仓库需包含 repo_owner（所有者）、repo_name（仓库名）、base_save_dir（基础保存目录）、state_key（状态标识）
repos:
  - repo_owner: "SychicBoy"          # 仓库所有者（GitHub用户名/组织名）
    repo_name: "NETReactorSlayer"    # 仓库名称
    base_save_dir: "./Releases"      # 基础保存目录（文件最终会按「基础目录/仓库名/版本号」存储）
    state_key: "NETReactorSlayer"    # 状态文件中的唯一标识（避免与其他仓库冲突）

  - repo_owner: "dnSpy"
    repo_name: "dnSpy"
    base_save_dir: "./Releases"
    state_key: "dnSpy"

  - repo_owner: "kingToolbox"
    repo_name: "WindTerm"
    base_save_dir: "./Releases"
    state_key: "WindTerm"
    
  - repo_owner: "x64dbg"
    repo_name: "x64dbg"
    base_save_dir: "./Releases"
    state_key: "x64dbg"

  - repo_owner: "NickeManarin"
    repo_name: "ScreenToGif"
    base_save_dir: "./Releases"
    state_key: "ScreenToGif"

  - repo_owner: "notepad-plus-plus"
    repo_name: "notepad-plus-plus"
    base_save_dir: "./Releases"
    state_key: "notepad-plus-plus"
