# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: UpdateVersion
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: tree
      run: |
        tree
    - name: Everything
      run: |
        python ./model/everything.py

    - name: Commit and Push Changes
      env:
        TZ: America/New_York
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m ":pencil: Auto update Edge at  $(date +"%Y-%m-%d %H:%M")" -a || echo "No changes to commit"
        git push origin main
        
        
