# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: UpdateVersion
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
#permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Prepare SSH key
      run: |
        mkdir -p ~/.ssh
          # 将私钥写入文件
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # 设置正确权限（必须为600，否则SSH会拒绝）
          chmod 600 ~/.ssh/id_rsa
          # 配置SSH以自动接受未知主机
          ssh-keyscan -p 10022 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: tree
      run: |
        tree
    - name: Everything
      run: |
        python ./model/everything.py
    - name: Transfer via SCP (10022端口)
      run: |
        # 关键：使用 -P 参数指定端口10022（SCP的端口参数是大写P）
        scp -P 10022 \
            -r ./download/ \
            root@${{ secrets.SSH_HOST }}:/root/zfile/data/000-自动更新
        # 如果目录为空，报错会继续执行
        continue-on-error: true
    - name: Commit and Push Changes
      if: always()
      env:
        TZ: Asia/Shanghai
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m ":pencil: Auto update Json at  $(date +"%Y-%m-%d %H:%M")" -a || echo "No changes to commit"
        git push origin main
        
        
